### ISSUE TITLE
Benchmarked code is unoptimized

### ISSUE THREAD

**Issue by dbaston** [varpande/spatial-libs#1]
The CMake configuration specifies optimization flags for the test harness, but these do not propagate to the code under test.

https://github.com/varpande/spatial-libs/blob/master/cpp/CMakeLists.txt#L73

When using this configuration, the GEOS source files are compiled with optimizations disabled.

**Comment by varpande** [comment]
Hi Dan. Thanks for raising the issue. Yes, you are correct, this line [https://github.com/varpande/spatial-libs/blob/master/cpp/CMakeLists.txt#L73]() only takes care of the benchmark code itself, and does not compile the underlying libraries with any optimization. I have mentioned in the README to use cmake -DCMAKE_BUILD_TYPE=Release .. which should take care of optimizing the build for the underlying libraries also. But I should enforce it in the CMakeList to make sure that in case the user does not specify the build type then the libraries should be compiled as Release.

**Comment by varpande** [comment]
This should fix the issue [https://github.com/varpande/spatial-libs/blob/master/cpp/CMakeLists.txt#L38](https://github.com/varpande/spatial-libs/blob/master/cpp/CMakeLists.txt#L38)
